### ISSUE TITLE
-f command

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/ygopro-salvation-custom#1]
https://github.com/sidschingis/Dev_ygopro/commit/66e57981f72d68df993a2dbfa70223a4c2b0e5cc
https://github.com/sidschingis/Dev_ygopro/commit/431299a2ffef96b552019b9674a19275fcfe1677

We need this feature for battle pack 3 support.

**Comment by Zayelion** [comment]
@adrianojn and @IngwiePhoenix I gave you guys commit access.

**Comment by adrianojn** [comment]
It seems that the **-f** option is no different of **-j** when "**forced =**" config option is disabled.

Should I remove **-f** or change it to _really_ force ("_force = 1_")?

**Comment by Zayelion** [comment]
The intended effect is when -f is used in place of -j the duelist is unable to select a deck and the deck in system.conf is uploaded. If the deck is invalid, no idea what should happen next, presumable exiting. This will allow the launcher to generate decks and then force the user to use it in a controlled environment. I apologize I cant elaborate beyond that.
