### ISSUE TITLE
Effects dont work

### ISSUE THREAD

**Issue by ghost** [SalvationDevelopment/ygopro-salvation-custom#10]
So i manged to compile buttys version of this how ever effects won't activate and i cant special summon. Also i get errors when i try to compile the latest ocg.dil in visual studios.

**Comment by Zayelion** [comment]
why are you compiling this in the first place?

**Comment by ghost** [comment]
Testing purposes.

**Comment by Zayelion** [comment]
Then this source code is useless to you, use https://github.com/Fluorohydride/ygopro

**Comment by ghost** [comment]
Thank you for the help.

**Comment by ghost** [comment]
The ocg.dill wont compile for me in vs. I have added lua.lib like the wiki suggested but i still get errors.

**Comment by Zayelion** [comment]
You are going to have to give me clear information on what you are trying to accomplish (if anything) for me to help you. Compiling this repo wont net you anything but a broken version of YGOPro. If you want a working version of YGOPro then compile  https://github.com/Fluorohydride/ygopro if you cant compile it  read this : https://github.com/SalvationDevelopment/YGOPro-Salvation-Server/blob/master/documentation/ocgcore.md and the reference information at the bottom.
