### ISSUE TITLE
Spectators usernames.

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/ygopro-salvation-custom#2]
https://github.com/Fluorohydride/ygopro/blob/de617a8048725215bc9f74a1b9bb56a45b3d7c3f/gframe/game.cpp

``` C++
default: //from watcher or unknown
        if(player < 11 || player > 19)
            chatMsg[0].append(L"[---]: ");
    }
```

username for spectators is not cached on game start, can this be taken care of in the client or does the server need to manipulate the data?

**Comment by adrianojn** [comment]
The simplest way is sending the username _as part_ of the chat message (gframe/event_handler.cpp:852). Checkmate does this but using the registered names on server.

**Comment by Zayelion** [comment]
https://github.com/SalvationDevelopment/YGOCore/commit/7f6d1594607717c3ab701c46bb04abb194729d57 Client side it doesnt show. I dont think that is a super major issue but it is an inconsistency.
