### ISSUE TITLE
Lock in disabled, Fatal error, Debug text

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/ygopro-salvation-custom#5]
Hey @adrianojn if Im bothering you let me know. I tested the latest code and it has two issues.

1.) From myself the deck selection lock in appears to be disabled, like the system is running in -f mode while in LAN or -j mode.
2.) When accessing host mode in LAN it errors out for Chibi
3.) Is it possible to enable the red error text to help the testers?

**Comment by adrianojn** [comment]
1. done
2. I need more info
3. on file `system.conf` set `errorlog = 1`

**Comment by Zayelion** [comment]
Steps to reproduce
1. Start in offline mode (opening ygopro.exe)
2. Press LAN
3. Enter details (unspecified, possibly none)
4. Press host

At this point the application per Chibi, "explodes". Im unable to reproduce this on my own system.

**Comment by adrianojn** [comment]
I can't reproduce the problem.

**Comment by Zayelion** [comment]
Can I get screenshot verification on point 3 and I think we can close this. Our next step is creating a delta to submit to FH for sound.

**Comment by adrianojn** [comment]
![sem titulo](https://cloud.githubusercontent.com/assets/6740848/9311516/186a5500-44ed-11e5-8fb5-aea0580d86b4.png)
